version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # @TODO Support wildcards: https://github.com/dependabot/dependabot-core/issues/2178

  - package-ecosystem: terraform
    directory: stacks/cac1-sample
    schedule:
      interval: daily
