name: Terraform

on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  issue_comment:
    types: [created, edited]

jobs:
  terraform: # Parse terraform command(s) from comment body and run on PR branch.

  # uses: rdhar/terraform-with-comments/.github/workflows/terraform.yml@main
    uses: ./.github/workflows/terraform.yml

    secrets:
      env_vars: |
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_PREFIX=sample
